/*
The code dfines and exports a set of constants typically used as action types
representing different states
Action types are string cosntants that represent the type of an action that is being
dispatched. They serve as identifiers for actions. These allow reducers to know how to update the state
*/






export const REGISTER_REQUEST="REGISTER_REQUEST"
export const REGISTER_SUCCESS="REGISTER_SUCCESS"
export const REGISTER_FAILURE="REGISTER_FAILURE"

export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAILURE="LOGIN_FAILURE"

export const LOGIN_TWO_STEP_REQUEST="LOGIN_TWO_STEP_REQUEST"
export const LOGIN_TWO_STEP_SUCCESS="LOGIN_TWO_STEP_SUCCESS"
export const LOGIN_TWO_STEP_FAILURE="LOGIN_TWO_STEP_FAILURE"

export const GET_USER_REQUEST="GET_USER_REQUEST"
export const GET_USER_SUCCESS="GET_USER_SUCCESS"
export const GET_USER_FAILURE="GET_USER_FAILURE"

export const SEND_VERIFICATION_REQUEST="SEND_VERIFICATION_REQUEST"
export const SEND_VERIFICATION_SUCCESS="SEND_VERIFICATION_SUCCESS"
export const SEND_VERIFICATION_FAILURE="SEND_VERIFICATION_FAILURE"


export const ENABLE_TWO_REQUEST="ENABLE_TWO_REQUEST"
export const ENABLE_TWO_SUCCESS="ENABLE_TWO_SUCCESS"
export const ENABLE_TWO_FAILURE="ENABLE_TWO_FAILURE"

export const ENABLE_TWO_STEP_AUTHENTICATION_REQUEST = "ENABLE_TWO_STEP_AUTHENTICATION_REQUEST"
export const ENABLE_TWO_STEP_AUTHENTICATION_SUCCESS = "ENABLE_TWO_STEP_AUTHENTICATION_SUCCESS"
export const ENABLE_TWO_STEP_AUTHENTICATION_FAILURE = "ENABLE_TWO_STEP_AUTHENTICATION_FAILURE"

export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST"
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS"
export const VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE"

export const SEND_RESET_PASSWORD_REQUEST = "SEND_RESET_PASSWORD_REQUEST"
export const SEND_RESET_PASSWORD_SUCCESS = "SEND_RESET_PASSWORD_SUCCESS"
export const SEND_RESET_PASSWORD_FAILURE = "SEND_RESET_PASSWORD_FAILURE"

export const VERIFY_RESET_PASSWORD_REQUEST = "VERIFY_RESET_PASSWORD_REQUEST"
export const VERIFY_RESET_PASSWORD_SUCCESS = "VERIFY_RESET_PASSWORD_SUCCESS"
export const VERIFY_RESET_PASSWORD_FAILURE = "VERIFY_RESET_PASSWORD_FAILURE"

export const LOG_OUT_SUCCESS="LOG_OUT_SUCCESS"
